# Intro

**Seminar by @Elad_Benjo**

In this part of EDA I will inspect our monthly indicators in order to identify patterns or hidden insights that can use as a lead for the Reduciton stage.

In [1]:
from google.colab import drive
import sys
import pandas as pd

drive.mount('/content/drive')
sys.path.append('/content/drive/MyDrive/gdp_nowcasting_seminar/src')

Mounted at /content/drive

In [2]:
merged_df = pd.read_pickle('/content/drive/MyDrive/gdp_nowcasting_seminar/Data/pickles/stationary/full_data.pkl')

# EDA

In [3]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 308 entries, 1995-01-01 to 2025-04-01
Data columns (total 61 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Total refunds from the Income Tax Department                                    286 non-null    float64
 1   Companies returns                                                               286 non-null    float64
 2   self employed returns                                                           286 non-null    float64
 3   Cancellations Deductions                                                        297 non-null    float64
 4   Capital Gas Tax Refunds                                                         296 non-null    float64
 5   Cancellation companies                                                          297 non-null    float64
 6   Purchase returns                                                                296 non-null    float64
 7   Independent Cancellations                                                       296 non-null    float64
 8   VAT refund autonomy and traders                                                 296 non-null    float64
 9   Unemployment rate (ages 25-64,  percentage pots)                                131 non-null    float64
 10  VAT_rate                                                                        306 non-null    float64
 11  Net local sales tax                                                             297 non-null    float64
 12  The combed dex of the state of the economy                                      275 non-null    float64
 13  Employment rate (ages 25-64)                                                    131 non-null    float64
 14  Participation rate (ages 25-64,  percentage pots)                               131 non-null    float64
 15  CPI                                                                             306 non-null    float64
 16  Industrial Production Index (Total)                                             213 non-null    float64
 17  cons_trust                                                                      231 non-null    float64
 18  Net customs                                                                     286 non-null    float64
 19  real_credit_card                                                                213 non-null    float64
 20  Credit card purchase value dices (total) (2002=100)                             214 non-null    float64
 21  Apartment Price Index (1993=100) - Mid-period reviewed                          304 non-null    float64
 22  Net import purchase tax                                                         286 non-null    float64
 23  Gross fuel tax                                                                  285 non-null    float64
 24  Total import taxes                                                              286 non-null    float64
 25  Gross import VAT                                                                286 non-null    float64
 26  salaried jobs                                                                   202 non-null    float64
 27  Gross local VAT                                                                 286 non-null    float64
 28  Total net VAT                                                                   286 non-null    float64
 29  Real Salary                                                                     131 non-null    float64
 30  Property tax                                                                    296 non-null    float64
 31  Apartments sold at an annual rate                                               274 non-null    float64
 32  Foreign exchange reserves  millions of dollars                                  305 non-null    float64
 33  excess expenses                                                                 287 non-null    float64
 34  VAT Fancial Institutions (Salary)                                               286 non-null    float64
 35  praise tax                                                                      286 non-null    float64
 36  Bonds and dividends                                                             296 non-null    float64
 37  Real estate purchase tax                                                        286 non-null    float64
 38  Goods and services                                                              286 non-null    float64
 39  Independents advances                                                           286 non-null    float64
 40  Self-employed tax differences                                                   286 non-null    float64
 41  Non-profit stitution tax                                                        286 non-null    float64
 42  Real estate taxation                                                            286 non-null    float64
 43  tax differential companies                                                      286 non-null    float64
 44  Companies advances                                                              286 non-null    float64
 45  Income tax for self-employed dividuals and companies (advances and deductions)  286 non-null    float64
 46  Deduction from salary                                                           286 non-null    float64
 47  Deductions and the capital market                                               286 non-null    float64
 48  Total Income Tax Division Net                                                   286 non-null    float64
 49  Total Gross Income Tax Division                                                 286 non-null    float64
 50  TA125                                                                           307 non-null    float64
 51  TA35                                                                            307 non-null    float64
 52  SP500                                                                           307 non-null    float64
 53  USD_ILS                                                                         307 non-null    float64
 54  SPGSCI                                                                          307 non-null    float64
 55  madad_yetzur_industrial                                                         307 non-null    float64
 56  madad_meshulav                                                                  307 non-null    float64
 57  madad_pedion                                                                    307 non-null    float64
 58  salaried_jobs_total_sa                                                          307 non-null    float64
 59  real_salary_avg_total_sa                                                        307 non-null    float64
 60  madad_cc_purchases_sa                                                           295 non-null    float64
dtypes: float64(61)
memory usage: 149.2 KB

## Correlation

In [4]:
import correlation_clustering

In [5]:
pairs = correlation_clustering.list_high_corr_pairs(merged_df, 0.75)

In [6]:
pairs

,var_i,var_j,rho,n_overlap
0,real_credit_card,Credit card purchase value dices (total) (2002...,0.999868,213
1,The combed dex of the state of the economy,madad_meshulav,0.996620,275
2,Net import purchase tax,Total import taxes,0.996417,286
3,Credit card purchase value dices (total) (2002...,madad_cc_purchases_sa,0.995408,214
4,real_credit_card,madad_cc_purchases_sa,0.995192,213
5,salaried jobs,salaried_jobs_total_sa,0.992724,202
6,TA125,TA35,0.980221,307
7,Total Income Tax Division Net,Total Gross Income Tax Division,0.964310,286
8,Total refunds from the Income Tax Department,Companies returns,0.963768,286
9,Real Salary,real_salary_avg_total_sa,0.955864,131
10,Employment rate (ages 25-64),"Participation rate (ages 25-64, percentage po...",0.888503,131
11,Real estate purchase tax,Real estate taxation,0.839921,286
12,praise tax,Real estate taxation,0.835030,286
13,Gross local VAT,Total net VAT,0.826101,286
14,Deduction from salary,Total Gross Income Tax Division,0.798940,286
15,Deductions and the capital market,Total Gross Income Tax Division,0.798893,286
16,real_credit_card,madad_pedion,0.795408,213
17,Credit card purchase value dices (total) (2002...,madad_pedion,0.794721,214
18,Deduction from salary,Total Income Tax Division Net,0.780438,286
19,Deduction from salary,Deductions and the capital market,0.778843,286
20,Deductions and the capital market,Total Income Tax Division Net,0.762428,286
21,madad_pedion,madad_cc_purchases_sa,0.762170,295
22,salaried jobs,real_salary_avg_total_sa,-0.822458,202
23,Real Salary,salaried_jobs_total_sa,-0.860185,131
24,salaried jobs,Real Salary,-0.864614,131

after evaluating these results I am applying these principals:
1. remove duplicates (I had several different sources of data)
2. keep the one with more availble records
3. pefer gross over net
4. do not remove economically related variables, these will be reduced to a factor together (example: real estate tax & praise tax, different income taxes etc.)

first items in table (0) are credit card purchases, that overalps almost completly, and then overlaps with the credit card index in item (4), since the cc index has significantly more records than the other two we can replace them.   
second item (1) overlaps almost completly with 'madad meshulav' which has more records.  
inspecting (5) and (9, 22-24) we can remove 'Real Salary' and 'salaried jobs'  
(7) remove 'Total Income Tax Division Net' and leave Gross

In [8]:
merged_df = merged_df.drop(columns=merged_df.columns[[1, 12, 19, 20, 22, 26, 29, 48 ,51]])

In [9]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 308 entries, 1995-01-01 to 2025-04-01
Data columns (total 52 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Total refunds from the Income Tax Department                                    286 non-null    float64
 1   self employed returns                                                           286 non-null    float64
 2   Cancellations Deductions                                                        297 non-null    float64
 3   Capital Gas Tax Refunds                                                         296 non-null    float64
 4   Cancellation companies                                                          297 non-null    float64
 5   Purchase returns                                                                296 non-null    float64
 6   Independent Cancellations                                                       296 non-null    float64
 7   VAT refund autonomy and traders                                                 296 non-null    float64
 8   Unemployment rate (ages 25-64,  percentage pots)                                131 non-null    float64
 9   VAT_rate                                                                        306 non-null    float64
 10  Net local sales tax                                                             297 non-null    float64
 11  Employment rate (ages 25-64)                                                    131 non-null    float64
 12  Participation rate (ages 25-64,  percentage pots)                               131 non-null    float64
 13  CPI                                                                             306 non-null    float64
 14  Industrial Production Index (Total)                                             213 non-null    float64
 15  cons_trust                                                                      231 non-null    float64
 16  Net customs                                                                     286 non-null    float64
 17  Apartment Price Index (1993=100) - Mid-period reviewed                          304 non-null    float64
 18  Gross fuel tax                                                                  285 non-null    float64
 19  Total import taxes                                                              286 non-null    float64
 20  Gross import VAT                                                                286 non-null    float64
 21  Gross local VAT                                                                 286 non-null    float64
 22  Total net VAT                                                                   286 non-null    float64
 23  Property tax                                                                    296 non-null    float64
 24  Apartments sold at an annual rate                                               274 non-null    float64
 25  Foreign exchange reserves  millions of dollars                                  305 non-null    float64
 26  excess expenses                                                                 287 non-null    float64
 27  VAT Fancial Institutions (Salary)                                               286 non-null    float64
 28  praise tax                                                                      286 non-null    float64
 29  Bonds and dividends                                                             296 non-null    float64
 30  Real estate purchase tax                                                        286 non-null    float64
 31  Goods and services                                                              286 non-null    float64
 32  Independents advances                                                           286 non-null    float64
 33  Self-employed tax differences                                                   286 non-null    float64
 34  Non-profit stitution tax                                                        286 non-null    float64
 35  Real estate taxation                                                            286 non-null    float64
 36  tax differential companies                                                      286 non-null    float64
 37  Companies advances                                                              286 non-null    float64
 38  Income tax for self-employed dividuals and companies (advances and deductions)  286 non-null    float64
 39  Deduction from salary                                                           286 non-null    float64
 40  Deductions and the capital market                                               286 non-null    float64
 41  Total Gross Income Tax Division                                                 286 non-null    float64
 42  TA125                                                                           307 non-null    float64
 43  SP500                                                                           307 non-null    float64
 44  USD_ILS                                                                         307 non-null    float64
 45  SPGSCI                                                                          307 non-null    float64
 46  madad_yetzur_industrial                                                         307 non-null    float64
 47  madad_meshulav                                                                  307 non-null    float64
 48  madad_pedion                                                                    307 non-null    float64
 49  salaried_jobs_total_sa                                                          307 non-null    float64
 50  real_salary_avg_total_sa                                                        307 non-null    float64
 51  madad_cc_purchases_sa                                                           295 non-null    float64
dtypes: float64(52)
memory usage: 127.5 KB

In [10]:
merged_df.to_pickle('/content/drive/MyDrive/gdp_nowcasting_seminar/Data/pickles/EDA/merged_data.pkl')

In [11]:
pairs2 = correlation_clustering.list_high_corr_pairs(merged_df, 0.75)

In [12]:
pairs2

,var_i,var_j,rho,n_overlap
0,Employment rate (ages 25-64),"Participation rate (ages 25-64, percentage po...",0.888503,131
1,Real estate purchase tax,Real estate taxation,0.839921,286
2,praise tax,Real estate taxation,0.835030,286
3,Gross local VAT,Total net VAT,0.826101,286
4,Deduction from salary,Total Gross Income Tax Division,0.798940,286
5,Deductions and the capital market,Total Gross Income Tax Division,0.798893,286
6,Deduction from salary,Deductions and the capital market,0.778843,286
7,madad_pedion,madad_cc_purchases_sa,0.762170,295

## Proxy

Resample the mothly data to quarterly

In [13]:
quarterly_merged_df = merged_df.resample("QE").mean()

In [14]:
quarterly_merged_df.to_pickle('/content/drive/MyDrive/gdp_nowcasting_seminar/Data/pickles/EDA/quarterly_merged_data.pkl')

In [15]:
quarterly_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 122 entries, 1995-03-31 to 2025-06-30
Freq: QE-DEC
Data columns (total 52 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Total refunds from the Income Tax Department                                    114 non-null    float64
 1   self employed returns                                                           114 non-null    float64
 2   Cancellations Deductions                                                        118 non-null    float64
 3   Capital Gas Tax Refunds                                                         118 non-null    float64
 4   Cancellation companies                                                          118 non-null    float64
 5   Purchase returns                                                                118 non-null    float64
 6   Independent Cancellations                                                       118 non-null    float64
 7   VAT refund autonomy and traders                                                 118 non-null    float64
 8   Unemployment rate (ages 25-64,  percentage pots)                                53 non-null     float64
 9   VAT_rate                                                                        121 non-null    float64
 10  Net local sales tax                                                             118 non-null    float64
 11  Employment rate (ages 25-64)                                                    53 non-null     float64
 12  Participation rate (ages 25-64,  percentage pots)                               53 non-null     float64
 13  CPI                                                                             121 non-null    float64
 14  Industrial Production Index (Total)                                             85 non-null     float64
 15  cons_trust                                                                      92 non-null     float64
 16  Net customs                                                                     114 non-null    float64
 17  Apartment Price Index (1993=100) - Mid-period reviewed                          121 non-null    float64
 18  Gross fuel tax                                                                  114 non-null    float64
 19  Total import taxes                                                              114 non-null    float64
 20  Gross import VAT                                                                114 non-null    float64
 21  Gross local VAT                                                                 114 non-null    float64
 22  Total net VAT                                                                   114 non-null    float64
 23  Property tax                                                                    118 non-null    float64
 24  Apartments sold at an annual rate                                               109 non-null    float64
 25  Foreign exchange reserves  millions of dollars                                  121 non-null    float64
 26  excess expenses                                                                 114 non-null    float64
 27  VAT Fancial Institutions (Salary)                                               114 non-null    float64
 28  praise tax                                                                      114 non-null    float64
 29  Bonds and dividends                                                             118 non-null    float64
 30  Real estate purchase tax                                                        114 non-null    float64
 31  Goods and services                                                              114 non-null    float64
 32  Independents advances                                                           114 non-null    float64
 33  Self-employed tax differences                                                   114 non-null    float64
 34  Non-profit stitution tax                                                        114 non-null    float64
 35  Real estate taxation                                                            114 non-null    float64
 36  tax differential companies                                                      114 non-null    float64
 37  Companies advances                                                              114 non-null    float64
 38  Income tax for self-employed dividuals and companies (advances and deductions)  114 non-null    float64
 39  Deduction from salary                                                           114 non-null    float64
 40  Deductions and the capital market                                               114 non-null    float64
 41  Total Gross Income Tax Division                                                 114 non-null    float64
 42  TA125                                                                           122 non-null    float64
 43  SP500                                                                           122 non-null    float64
 44  USD_ILS                                                                         122 non-null    float64
 45  SPGSCI                                                                          122 non-null    float64
 46  madad_yetzur_industrial                                                         122 non-null    float64
 47  madad_meshulav                                                                  122 non-null    float64
 48  madad_pedion                                                                    122 non-null    float64
 49  salaried_jobs_total_sa                                                          122 non-null    float64
 50  real_salary_avg_total_sa                                                        122 non-null    float64
 51  madad_cc_purchases_sa                                                           118 non-null    float64
dtypes: float64(52)
memory usage: 50.5 KB

In [ ]:
monthly_df.to_csv('/content/drive/MyDrive/gdp_nowcasting_seminar/Data/formatted_CSVs/for_r/monthly_data.csv')

In [16]:
quarterly_df = pd.read_pickle('/content/drive/MyDrive/gdp_nowcasting_seminar/Data/pickles/stationary/quarterly_data.pkl')

In [17]:
quarterly_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 119 entries, 1995-06-30 to 2024-12-31
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GDP     119 non-null    float64
 1   C       119 non-null    float64
 2   G       115 non-null    float64
 3   I       119 non-null    float64
 4   EX      119 non-null    float64
 5   IM      119 non-null    float64
dtypes: float64(6)
memory usage: 6.5 KB

In [ ]:
quarterly_df.to_csv('/content/drive/MyDrive/gdp_nowcasting_seminar/Data/formatted_CSVs/for_r/quarterly_data.csv')

In [ ]:
quarterly_df.describe()

              GDP           C           G           I          EX          IM
count  119.000000  119.000000  115.000000  119.000000  119.000000  119.000000
mean     0.009132    0.009548    0.000037    0.007388    0.011957    0.010154
std      0.016473    0.021680    0.025058    0.062635    0.043540    0.040186
min     -0.086301   -0.122846   -0.133232   -0.306142   -0.177674   -0.114879
25%      0.002563    0.003015   -0.010309   -0.021964   -0.010088   -0.010720
50%      0.009972    0.009566    0.001903    0.008510    0.013298    0.013631
75%      0.015727    0.017629    0.009611    0.038962    0.036021    0.032206
max      0.085868    0.080171    0.159026    0.185486    0.165703    0.169621

In [18]:
# Align the dataframes by index
aligned_df = quarterly_merged_df.align(quarterly_df['GDP'], join='inner', axis=0)
quarterly_monthly_aligned = aligned_df[0]
quarterly_gdp_aligned = aligned_df[1]

# Calculate the correlation between GDP and each column in quarterly_monthly_df
correlations = quarterly_monthly_aligned.corrwith(quarterly_gdp_aligned)

# Find the column with the highest absolute correlation
most_correlated_column = correlations.abs().idxmax()
highest_correlation_value = correlations[most_correlated_column]

print(f"The column in quarterly_monthly_df with the highest correlation to GDP is: {most_correlated_column}")
print(f"The correlation coefficient is: {highest_correlation_value}")

The column in quarterly_monthly_df with the highest correlation to GDP is: salaried_jobs_total_sa
The correlation coefficient is: 0.5790178780404449

In [19]:
quarterly_monthly_aligned.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 119 entries, 1995-06-30 to 2024-12-31
Data columns (total 52 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Total refunds from the Income Tax Department                                    112 non-null    float64
 1   self employed returns                                                           112 non-null    float64
 2   Cancellations Deductions                                                        116 non-null    float64
 3   Capital Gas Tax Refunds                                                         116 non-null    float64
 4   Cancellation companies                                                          116 non-null    float64
 5   Purchase returns                                                                116 non-null    float64
 6   Independent Cancellations                                                       116 non-null    float64
 7   VAT refund autonomy and traders                                                 116 non-null    float64
 8   Unemployment rate (ages 25-64,  percentage pots)                                52 non-null     float64
 9   VAT_rate                                                                        119 non-null    float64
 10  Net local sales tax                                                             116 non-null    float64
 11  Employment rate (ages 25-64)                                                    52 non-null     float64
 12  Participation rate (ages 25-64,  percentage pots)                               52 non-null     float64
 13  CPI                                                                             119 non-null    float64
 14  Industrial Production Index (Total)                                             84 non-null     float64
 15  cons_trust                                                                      91 non-null     float64
 16  Net customs                                                                     112 non-null    float64
 17  Apartment Price Index (1993=100) - Mid-period reviewed                          119 non-null    float64
 18  Gross fuel tax                                                                  112 non-null    float64
 19  Total import taxes                                                              112 non-null    float64
 20  Gross import VAT                                                                112 non-null    float64
 21  Gross local VAT                                                                 112 non-null    float64
 22  Total net VAT                                                                   112 non-null    float64
 23  Property tax                                                                    116 non-null    float64
 24  Apartments sold at an annual rate                                               108 non-null    float64
 25  Foreign exchange reserves  millions of dollars                                  119 non-null    float64
 26  excess expenses                                                                 112 non-null    float64
 27  VAT Fancial Institutions (Salary)                                               112 non-null    float64
 28  praise tax                                                                      112 non-null    float64
 29  Bonds and dividends                                                             116 non-null    float64
 30  Real estate purchase tax                                                        112 non-null    float64
 31  Goods and services                                                              112 non-null    float64
 32  Independents advances                                                           112 non-null    float64
 33  Self-employed tax differences                                                   112 non-null    float64
 34  Non-profit stitution tax                                                        112 non-null    float64
 35  Real estate taxation                                                            112 non-null    float64
 36  tax differential companies                                                      112 non-null    float64
 37  Companies advances                                                              112 non-null    float64
 38  Income tax for self-employed dividuals and companies (advances and deductions)  112 non-null    float64
 39  Deduction from salary                                                           112 non-null    float64
 40  Deductions and the capital market                                               112 non-null    float64
 41  Total Gross Income Tax Division                                                 112 non-null    float64
 42  TA125                                                                           119 non-null    float64
 43  SP500                                                                           119 non-null    float64
 44  USD_ILS                                                                         119 non-null    float64
 45  SPGSCI                                                                          119 non-null    float64
 46  madad_yetzur_industrial                                                         119 non-null    float64
 47  madad_meshulav                                                                  119 non-null    float64
 48  madad_pedion                                                                    119 non-null    float64
 49  salaried_jobs_total_sa                                                          119 non-null    float64
 50  real_salary_avg_total_sa                                                        119 non-null    float64
 51  madad_cc_purchases_sa                                                           116 non-null    float64
dtypes: float64(52)
memory usage: 49.3 KB

In [20]:
correlations = correlations.sort_values(ascending=False)

In [25]:
print(correlations[0:5])

salaried_jobs_total_sa                                0.579018
madad_meshulav                                        0.484566
Employment rate (ages 25-64)                          0.309802
Goods and services                                    0.219763
Participation rate (ages 25-64,  percentage pots)     0.160584
dtype: float64

In [26]:
import eda

In [29]:
quarterly_monthly_aligned = quarterly_monthly_aligned.join(quarterly_gdp_aligned)

In [37]:
eda.plot_time_series_altair(quarterly_monthly_aligned.iloc[0:, [49, 52, 47]], "Series Correlation With GDP Q")

alt.Chart(...)